### ISSUE TITLE
Browser tab recognition - add a recognisable icon

### ISSUE THREAD

**Issue by Tyrbiter** [tonyc/open890#106]
Could a nice colourful icon be added so that the browser in use shows an easy to spot tab?

I'm an inveterate tab user and finding the right one is a lot easier with a visual cue.

This could also stand as a project badge on github.

**Comment by tonyc** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/10182/206465700-1b8cd4b9-5ba1-4bf2-8f14-14f7636df14f.png)

Not exactly "colorful" I guess - but it would fit the Kenwood aesthetic :)

There are some other tricks I could do, like dynamically changing the icon based on e.g. mode changes. So it could show "890" for a few seconds and then cycle to "USB", and then back.

**Comment by Tyrbiter** [comment]
That's certainly possible. I was wondering about the little icon that appears on the radio when KNS is active as the basis for this, but I'm not in a position to insist :)

Whatever you think appropriate, you're the one who has done all the work :)
