### ISSUE TITLE
Window Layout vs Mouse Wheel

### ISSUE THREAD

**Issue by RafalLukawiecki** [tonyc/open890#119]
I would prefer to be able to disable the mouse wheel frequency change function altogether, unless a different layout of the window was available. When I have open890 on the screen it is often in a half-height window, because I do not have the real estate for the full version. If there was a more "horizontal" version of the UI I would prefer it to the current one. The width matters, because of the amount of detail I need to see in the waterfall.

In general, on macOS, the mouse wheel scrolls windows even if they are **not** in focus. This is a long-time, great system-wide functionality. When I want to do that with the half-height open890 I end up, by mistake, retuning the radio to some random frequency. :) I have to remind myself not to use the mouse wheel for window scrolling in the open890, and to use the old-fashioned scroll bars. If I could disable that function, I would hope to be able to use the wheel for scrolling. I attach a screenshot of my desktop to show the layout real estate issue.

<img width="2559" alt="CQ WPX CW 2023 Desktop" src="https://github.com/tonyc/open890/assets/22912705/eee9e107-3e3d-4c19-9f74-7e87f611bd6d">

**Comment by tonyc** [comment]
@RafalLukawiecki I'm curious if the pop-out bandscope version works for your needs, i.e. browse to `/connections` in your browser window, and then click "Bandscope". This would eliminate the need for any scrolling, unless you still need the upper VFO display or the side panel.
