### ISSUE TITLE
Mising "Theme" and a big SEND button...

### ISSUE THREAD

**Issue by lb5va** [tonyc/open890#121]
The "Theme" selection that is shown in an older Youtube-video is no longer present. Or maybe not found by me..?
Maybe suggestions is not here but as you hide the buttons on the left side of scope, also the SEND button disappears.
It should be up on the main part of screen. Also driven by the space-bar, last button pressed...?
Macro buttons also not found after configuration them. Else - love this app!  :-)

**Comment by tonyc** [comment]
The theme selector shown in the really early videos ended up not panning out, as I decided to just stick with a "Kenwood" theme :)  I will look into moving the position of the SEND button. Thank you for your input!
