### ISSUE TITLE
Top-level KNS admin users cannot connect

### ISSUE THREAD

**Issue by tonyc** [tonyc/open890#78]
It looks like the connection string is not sending the "is admin" flag string properly in the `##ID` command - it is always sending a `1`, but should send `0` for admins.

**Comment by tonyc** [comment]
Additionally, the login process was waiting for a `##TI` response, which is not sent for admins.

**Comment by tonyc** [comment]
Fixed in 68d8509d1c4e30b628ca96e39d94a5885f3120d1

**Comment by Tyrbiter** [comment]
Tested this here and it is working fine for my administrator ID now.

Thanks for the fix.
