### ISSUE TITLE
Waterfall filter indicator incorrect when in FSK mode

### ISSUE THREAD

**Issue by RafalLukawiecki** [tonyc/open890#97]
I have noticed that the filter indicator seems to be away from the centre frequency when operating in FSK mode. This does NOT always happen, usually when changing bands or modes. It is as if the calculation for the location of the filter switched between using the MARK frequency and the frequency of MARK with the usual LSB offset. See screenshot below. The Tx and Rx point to the correct frequency, but the filter marker is off by over 2 kHz lower down.

![Screenshot 2022-08-20 at 23 27 25](https://user-images.githubusercontent.com/22912705/186739056-d4b0bf32-aaef-4ca0-b9ea-616ee29d68ae.png)

**Comment by tonyc** [comment]
Thanks for the report!

**Comment by RafalLukawiecki** [comment]
Perhaps this may help: the issue happens when switching bands. The fix is to change mode on the radio from FSK to CW and then back to FSK. At that point the width of the filter passband returns to where it should be.

**Comment by tonyc** [comment]
@RafalLukawiecki I believe I've managed to track this one down - thank you for the clue! It is committed to `main` and `develop`, and will be included in the next release as well.

**Comment by RafalLukawiecki** [comment]
Many thanks, @tonyc. I will reply once I had a chance to test it again.
