### ISSUE TITLE
Notch drag bar not centered

### ISSUE THREAD

**Issue by Tyrbiter** [tonyc/open890#98]
As for the title, the notch drag bar seems to be left justified.

**Comment by tonyc** [comment]
Thanks! I thought I had it centered at one point, but it must have reverted. I'll get it fixed up before 1.0.0 is actually released.

**Comment by Tyrbiter** [comment]
Just thought I'd mention it, yes it was fine but I suppose it's down to changes in the Tx/Ant tab affecting that whole area.

**Comment by tonyc** [comment]
@Tyrbiter I've made some UI tweaks around the slider, I've re-centered the notch indicator and added some border-radius so they look a little nicer. The changes are on `develop` and `main` branches, I plan on re-cutting the 1.0.0-pre release today.

![image](https://user-images.githubusercontent.com/10182/200169284-5450a793-b98f-4c98-8879-45dc5b69d236.png)

**Comment by Tyrbiter** [comment]
Had a quick look and it is now fixed, quite a nice look overall.
